#133 Update openmrs-module-shr-cdahandler to OpenMRS v2
SEDISH/openmrs-module-shr-cdahandler pull request #2
Opened 2017-07-12 15:01 UTC by areklalo

2017-07-14 11:36 UTC, pgesek requested changes

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/CdaImportService.java
> +import org.openmrs.*;
This is not a big deal, but a general practice is to avoid start imports - please turn this off in IntelliJ

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/CdaImportService.java
> +import org.openmrs.*;
Would probably be good to unwrap all these start imports

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/CdaImportService.java
> +import org.openmrs.*;
Well they already have them like this in other places, so it's fine - but for the future we want to avoid them

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					Patient patient=new Patient(obs.getPerson());
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					ConditionService conditionService=Context.getService(ConditionService.class);
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					for(Condition p : conditionService.getActiveConditions(patient)){
space before {

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					for(Allergy a: allergyService.getAllergies(new Patient(obs.getPerson()))){
space after a, rename a to allergy

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					for(Allergy a: allergyService.getAllergies(new Patient(obs.getPerson()))){
space before {

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					PatientService allergyService=Context.getPatientService();
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +						conditionService.voidCondition(p,voidReason);
space after comma

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		if(res.getAllergen()==null) res.setAllergen(new Allergen());
spaces around ==

try to avoid inline ifs

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +			Concept concept=this.m_conceptUtil.getOrCreateConcept(observation.getParticipant().get(0).getParticipantRole().getPlayingEntityChoiceIfPlayingEntity().getCode());
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +			Concept concept=obs.getValueCoded();
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		else if(obs.getValueCoded() != null){
space before {

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +			throw new DocumentImportException("Allergen must be of type CD");
Is this error message appropriate  given the checks above?

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +			if(reactionConcept!=null)
add spaces around !=

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +				res.addReaction(new AllergyReaction(res,reactionConcept,null));
is your space key busted?

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +				previousItem=getConditionByObs(obs,encounterInfo.getPatient());
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +				previousItem=getAllergyByObs(obs,encounterInfo.getPatient());
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +				previousItem=getAllergyByObs(obs,encounterInfo.getPatient());
and after comma

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +	private BaseOpenmrsData getAllergyByObs(Obs obs,Patient patient){
spaces

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +    private BaseOpenmrsData getConditionByObs(Obs obs, Patient patient){
space before {

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +	protected void updateItem(Condition res,Act act, ExtendedObs obs) throws DocumentImportException {
spaces

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +			PatientService allergyService=Context.getPatientService();
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +			Allergies allergies=allergyService.getAllergies(patient);
add spaces around =

2017-07-14 11:36 UTC, pgesek commented on api/src/test/resources/include/CdaImportTest.xml
> +  <!--
we should rather remove this

2017-07-14 13:13 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/CdaImportService.java
> +import org.openmrs.*;
Corrected.

2017-07-14 13:13 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					ConditionService conditionService=Context.getService(ConditionService.class);
Corrected.

2017-07-14 13:13 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					for(Condition p : conditionService.getActiveConditions(patient)){
Corrected.

2017-07-14 13:13 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +						conditionService.voidCondition(p,voidReason);
Corrected.

2017-07-14 13:13 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					PatientService allergyService=Context.getPatientService();
Corrected.

2017-07-14 13:14 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					for(Allergy a: allergyService.getAllergies(new Patient(obs.getPerson()))){
Corrected.

2017-07-14 13:14 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					for(Allergy a: allergyService.getAllergies(new Patient(obs.getPerson()))){
Corrected.

2017-07-14 13:14 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		if(res.getAllergen()==null) res.setAllergen(new Allergen());
Corrected.

2017-07-14 13:14 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +			Concept concept=this.m_conceptUtil.getOrCreateConcept(observation.getParticipant().get(0).getParticipantRole().getPlayingEntityChoiceIfPlayingEntity().getCode());
Corrected.

2017-07-14 13:14 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		else if(obs.getValueCoded() != null){
Corrected.

2017-07-14 13:14 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +			Concept concept=obs.getValueCoded();
Corrected.

2017-07-14 13:14 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +			if(reactionConcept!=null)
Corrected.

2017-07-14 13:16 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +				res.addReaction(new AllergyReaction(res,reactionConcept,null));
No :) Now will be fine. Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +				previousItem=getConditionByObs(obs,encounterInfo.getPatient());
Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +				previousItem=getAllergyByObs(obs,encounterInfo.getPatient());
Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +    private BaseOpenmrsData getConditionByObs(Obs obs, Patient patient){
Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +	private BaseOpenmrsData getAllergyByObs(Obs obs,Patient patient){
Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +	protected void updateItem(Condition res,Act act, ExtendedObs obs) throws DocumentImportException {
Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +			PatientService allergyService=Context.getPatientService();
Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +			Allergies allergies=allergyService.getAllergies(patient);
Corrected.

2017-07-14 13:17 UTC, areklalo commented on api/src/test/resources/include/CdaImportTest.xml
> +  <!--
Removed.

2017-07-18 07:36 UTC, mkruszynski requested changes
I've added a lot of duplicated comments with Java code conventions fixes. Try to fix as much as you can. Maybe a IntelliJ Search or Replace will be helpful.
I think that if we are correcting the module code, we can also improve a code quality :)

If you find more incompatibilities feel free to correct them.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/db/CdaImportServiceDAO.java
> +import org.openmrs.*;
Avoid a wildcard imports. You can set this in IntelliJ in File -> Settings -> Editor -> Code Style -> Java. There you can check a _Use single class import_ and increase a values in fields _Class count to use import with '*'_ and _Names count to use static import with '*'_ to some big value e.g. 50.

Additionally you can set an optimization of imports in File -> Settings -> Editor -> General -> Auto Import.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/db/hibernate/HibernateCdaImportServiceDAO.java
> +import org.openmrs.*;
Correct this wildcard.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/impl/CdaImportServiceImpl.java
>  import org.openmrs.*;
Correct this wildcard.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +import org.openmrs.*;
Correct this wildcard.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +import org.openmrs.*;
Correct this wildcard.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +				observation.getParticipant().get(0).getParticipantRole().getPlayingEntityChoiceIfPlayingEntity().getCode() != null){
Add a space around bracket

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +import org.openmrs.module.emrapi.conditionslist.contract.*;
Correct this wildcard.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
>  				{
If you notice some brackets in new line try to correct this to follow the conventions given e.g. by Oracle.[Here is a document with conventions](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf). A bracket should be in the same line with _if_, _for_, _else_, class definition etc.

Remove line break, add spaces.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
>  			for(Order ord : enc.getOrders())
Add a bracket in this line or remove the lline break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		if(res.getAllergen() == null)
Add a brackets to this _if_.

Avoid one-line conditions or loops.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		else if(obs.getValueCoded() != null) {
Remove line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		}
Remove line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		else
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  				observation.getCode().getCode().equals("FNAINT"))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(observation.getCode().getCode().equals("DALG") ||
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(observation.getCode().getCode().equals("EALG") ||
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  			if(severityObservationValue.getCode().equals("L"))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  			if(severityObservationValue.getCode().equals("M"))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  			if(severityObservationValue.getCode().equals("H"))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(observation.getCode().getCode().endsWith("INT"))
Remove line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		if(manifestationRelationship.size() == 1) // Only if there is one
Remove line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(manifestationRelationship.size() > 1)
Remove line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +import org.openmrs.*;
Correct that wildcard.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		if(res.getOnsetDate() == null && res.getEndDate() == null)
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		else if(res.getOnsetDate() != null && res.getEndDate() == null)
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  		for(Reference reference : act.getReference())
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  				!reference.getTypeCode().getCode().equals(x_ActRelationshipExternalReference.RPLC))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			else if(Allergy.class.isAssignableFrom(clazz))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			else if(Condition.class.isAssignableFrom(clazz))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			if(Allergy.class.isAssignableFrom(clazz))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			else if(Condition.class.isAssignableFrom(clazz))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  			if(existingItem != null && this.m_configuration.getUpdateExisting())
Add a brackets in this condition.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  		if(previousItem == null && obs.getPreviousVersion() != null)
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  			else if(existingItem != null)
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			if(Condition.class.isAssignableFrom(clazz))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  		if(res.getDateCreated() == null)
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  				act.getStatusCode().getCode() == ActStatus.Suspended)
Remove this line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		if(Allergy.class.isAssignableFrom(clazz))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			if(obs.getValueCoded().equals(condition.getConcept()))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +    	for(Allergy allergy : Context.getPatientService().getAllergies(patient)){
Add a space

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		for(Condition condition : Context.getService(ConditionService.class).getActiveConditions(patient)){
Add a space

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +    		if(obs.getValueCoded().equals(allergy.getAllergen().getCodedAllergen()))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
>  		if(!statement.getTemplateId().contains(new II(CdaHandlerConstants.ENT_TEMPLATE_PROBLEM_OBSERVATION)))
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
>  		if(obs.getValueCoded() == null)
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
>  		if(act.getNegationInd() != null && act.getNegationInd().toBoolean())
Add a brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +		if(act.getEffectiveTime() != null)
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +			if(act.getEffectiveTime().getLow() != null && !act.getEffectiveTime().getLow().isNull())
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +				if(res.getOnsetDate() == null || act.getEffectiveTime().getLow().getDateValue().getTime().compareTo(res.getOnsetDate()) < 0)
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +			if(act.getEffectiveTime().getHigh() != null && !act.getEffectiveTime().getHigh().isNull())
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +				if(res.getEndDate() == null || act.getEffectiveTime().getHigh().getDateValue().getTime().compareTo(res.getEndDate()) > 0)
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +		else if(act.getStatusCode().getCode() != ActStatus.Completed)
Add brackets.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/LocationOrganizationProcessorUtil.java
>  		if(organization.getId() != null)
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/LocationOrganizationProcessorUtil.java
>  		else if(organization.getName() != null && !organization.getName().isEmpty())
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
>  		if(concept == null && this.m_configuration.getAutoCreateConcepts())
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +import org.openmrs.*;
Correct that wildcard.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
>  		try
Remove a line break.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
>  			for(II id : ids)
Remove a line breaks in this block.

2017-07-18 07:36 UTC, mkruszynski commented on api/src/test/java/org/openmrs/module/shr/cdahandler/api/impl/test/CdaImportServiceImplTest.java
> +import org.openmrs.*;
Correct this wildcard.

2017-07-18 08:30 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/db/CdaImportServiceDAO.java
> +import org.openmrs.*;
Corrected, thanks for tip.

2017-07-18 08:31 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/db/hibernate/HibernateCdaImportServiceDAO.java
> +import org.openmrs.*;
Corrected.

2017-07-18 08:35 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/impl/CdaImportServiceImpl.java
>  import org.openmrs.*;
Corrected.

2017-07-18 08:37 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +import org.openmrs.*;
Corrected.

2017-07-18 08:38 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +import org.openmrs.module.emrapi.conditionslist.contract.*;
Corrected.

2017-07-18 08:38 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
> +					Patient patient=new Patient(obs.getPerson());
Corrected.

2017-07-18 08:41 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +import org.openmrs.*;
Corrected.

2017-07-18 08:48 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +				observation.getParticipant().get(0).getParticipantRole().getPlayingEntityChoiceIfPlayingEntity().getCode() != null){
Corrected.

2017-07-18 08:52 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		}
Corrected.

2017-07-18 08:52 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
> +		else
Corrected.

2017-07-18 08:53 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  				observation.getCode().getCode().equals("FNAINT"))
Corrected.

2017-07-18 08:55 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(observation.getCode().getCode().equals("DALG") ||
Corrected.

2017-07-18 08:55 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(observation.getCode().getCode().equals("EALG") ||
Corrected.

2017-07-18 08:55 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else
Corrected.

2017-07-18 08:55 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  			if(severityObservationValue.getCode().equals("L"))
Corrected.

2017-07-18 08:56 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  			if(severityObservationValue.getCode().equals("M"))
Corrected.

2017-07-18 08:56 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  			if(severityObservationValue.getCode().equals("H"))
Corrected.

2017-07-18 08:56 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(observation.getCode().getCode().endsWith("INT"))
Corrected.

2017-07-18 08:57 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else
Corrected.

2017-07-18 08:57 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		if(manifestationRelationship.size() == 1) // Only if there is one
Corrected.

2017-07-18 09:04 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		else if(manifestationRelationship.size() > 1)
Corrected.

2017-07-18 09:15 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +import org.openmrs.*;
Corrected.

2017-07-18 09:15 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		if(res.getOnsetDate() == null && res.getEndDate() == null)
Corrected.

2017-07-18 09:16 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		else if(res.getOnsetDate() != null && res.getEndDate() == null)
Corrected.

2017-07-18 09:16 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  		for(Reference reference : act.getReference())
Corrected.

2017-07-18 09:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  				!reference.getTypeCode().getCode().equals(x_ActRelationshipExternalReference.RPLC))
Corrected.

2017-07-18 09:18 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			else if(Allergy.class.isAssignableFrom(clazz))
Corrected.

2017-07-18 09:18 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			else if(Condition.class.isAssignableFrom(clazz))
Corrected.

2017-07-18 09:18 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			if(Allergy.class.isAssignableFrom(clazz))
Corrected.

2017-07-18 09:19 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			else if(Condition.class.isAssignableFrom(clazz))
Corrected.

2017-07-18 09:19 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  			if(existingItem != null && this.m_configuration.getUpdateExisting())
Corrected.

2017-07-18 09:20 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  			else if(existingItem != null)
Corrected.

2017-07-18 09:20 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  		if(previousItem == null && obs.getPreviousVersion() != null)
Corrected.

2017-07-18 09:21 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			if(Condition.class.isAssignableFrom(clazz))
Corrected.

2017-07-18 09:21 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  		if(res.getDateCreated() == null)
Corrected.

2017-07-18 09:24 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
>  				act.getStatusCode().getCode() == ActStatus.Suspended)
Corrected.

2017-07-18 09:24 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		if(Allergy.class.isAssignableFrom(clazz))
Corrected.

2017-07-18 09:24 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +		for(Condition condition : Context.getService(ConditionService.class).getActiveConditions(patient)){
Corrected.

2017-07-18 09:25 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +			if(obs.getValueCoded().equals(condition.getConcept()))
Corrected.

2017-07-18 09:25 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +    	for(Allergy allergy : Context.getPatientService().getAllergies(patient)){
Corrected.

2017-07-18 09:25 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConcernEntryProcessor.java
> +    		if(obs.getValueCoded().equals(allergy.getAllergen().getCodedAllergen()))
Corrected.

2017-07-18 09:26 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
>  		if(!statement.getTemplateId().contains(new II(CdaHandlerConstants.ENT_TEMPLATE_PROBLEM_OBSERVATION)))
Corrected.

2017-07-18 09:29 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
>  		if(obs.getValueCoded() == null)
Corrected.

2017-07-18 09:29 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
>  		if(act.getNegationInd() != null && act.getNegationInd().toBoolean())
Corrected.

2017-07-18 09:30 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +		if(act.getEffectiveTime() != null)
Corrected.

2017-07-18 09:30 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +			if(act.getEffectiveTime().getLow() != null && !act.getEffectiveTime().getLow().isNull())
Corrected.

2017-07-18 09:30 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +				if(res.getOnsetDate() == null || act.getEffectiveTime().getLow().getDateValue().getTime().compareTo(res.getOnsetDate()) < 0)
Corrected.

2017-07-18 09:30 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +			if(act.getEffectiveTime().getHigh() != null && !act.getEffectiveTime().getHigh().isNull())
Corrected.

2017-07-18 09:30 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +				if(res.getEndDate() == null || act.getEffectiveTime().getHigh().getDateValue().getTime().compareTo(res.getEndDate()) > 0)
Corrected.

2017-07-18 09:31 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/ConditionConcernEntryProcessor.java
> +		else if(act.getStatusCode().getCode() != ActStatus.Completed)
Corrected.

2017-07-18 09:37 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/LocationOrganizationProcessorUtil.java
>  		if(organization.getId() != null)
Corrected.

2017-07-18 09:37 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/LocationOrganizationProcessorUtil.java
>  		else if(organization.getName() != null && !organization.getName().isEmpty())
Corrected.

2017-07-18 09:58 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
>  		if(concept == null && this.m_configuration.getAutoCreateConcepts())
Corrected.

2017-07-18 10:00 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +import org.openmrs.*;
Corrected.

2017-07-18 10:01 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
>  		try
Corrected.

2017-07-18 10:09 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
>  			for(II id : ids)
Corrected.

2017-07-18 10:12 UTC, areklalo commented on api/src/test/java/org/openmrs/module/shr/cdahandler/api/impl/test/CdaImportServiceImplTest.java
> +import org.openmrs.*;
Corrected.

2017-07-18 10:17 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
>  			for(Order ord : enc.getOrders())
Corrected.

2017-07-18 12:21 UTC, mkruszynski requested changes

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/impl/CdaImportServiceImpl.java
> +	public Visit importDocument(InputStream doc) throws DocumentImportException
Bracket should be on the same line as method declaration. Please remove new line here

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
>  				{
Please remove a new line in this _if_ statement

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
>  				{
This bracket can be placed one line higher, before a comment

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
> +				if (foundConcept != null) break;
Add a brackets to this _if_

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
> +		{
Again, you can put this bracket higher, before comment

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
> +		if (candidateDrugWithMatchingForm != null)// found one
Put this bracket higher

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
>  		{
This bracket too :)

2017-07-18 12:21 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +				{
Bracket one line higher, as in previous files

2017-07-18 13:38 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
>  				{
Corrected.

2017-07-18 13:44 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/api/impl/CdaImportServiceImpl.java
> +	public Visit importDocument(InputStream doc) throws DocumentImportException
Corrected.

2017-07-18 13:45 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
>  				{
Corrected.

2017-07-18 13:45 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
> +				if (foundConcept != null) break;
Corrected.

2017-07-18 13:46 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
> +		{
Corrected.

2017-07-18 13:46 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
> +		if (candidateDrugWithMatchingForm != null)// found one
Corrected.

2017-07-18 13:50 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsConceptUtil.java
>  		{
Corrected.

2017-07-18 13:51 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +				{
Corrected.

2017-07-19 12:03 UTC, mkruszynski requested changes
@areklalo I found a couple of brackets that aren't replaced. Please fix this.

2017-07-19 12:03 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
>  		{
You forgot about this bracket.

2017-07-19 12:03 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		{
Put this bracket higher

2017-07-19 12:03 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/DatatypeProcessorUtil.java
> +			if(!m.getName().startsWith("get"))
Add brackets

2017-07-19 12:03 UTC, mkruszynski commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/DatatypeProcessorUtil.java
>  				{
Put this bracket one line higher

2017-07-19 12:56 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/document/impl/DocumentProcessorImpl.java
>  		{
Corrected.

2017-07-19 12:57 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/entry/impl/ihe/pcc/AllergiesAndIntolerancesConcernEntryProcessor.java
>  		{
Corrected.

2017-07-19 12:58 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/DatatypeProcessorUtil.java
> +			if(!m.getName().startsWith("get"))
Corrected.

2017-07-19 13:08 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/DatatypeProcessorUtil.java
>  				{
Corrected.

2017-07-19 13:25 UTC, mkruszynski approved these changes
@pgesek It looks good to me.

2017-07-19 13:27 UTC, merged