Fixes obs group issue
SEDISH/openmrs-module-shr-cdahandler pull request #5
Opened 2018-02-08 09:37 UTC by areklalo

2018-02-12 11:09 UTC, pgesek requested changes

2018-02-12 11:09 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +            }
Fix identation

2018-02-12 11:09 UTC, pgesek commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +			medicationHistoryObs.setValueText("This observation represent obs group");	//this is added to avoid error.noValue
Fix identation

2018-02-13 07:39 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +            }
Changed

2018-02-13 07:39 UTC, areklalo commented on api/src/main/java/org/openmrs/module/shr/cdahandler/processor/util/OpenmrsDataUtil.java
> +			medicationHistoryObs.setValueText("This observation represent obs group");	//this is added to avoid error.noValue
Changed

2018-02-13 10:34 UTC, pgesek approved these changes

2018-02-13 10:34 UTC, merged